In [1]:
from fredapi import Fred
import requests
import matplotlib
import matplotlib.pyplot as plt
import pandas as pd

ImportError: Unable to import required dependencies:
numpy:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.8 from "/Users/officialbiznas/anaconda3/envs/fin/bin/python"
  * The NumPy version is: "1.19.1"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: dlopen(/Users/officialbiznas/anaconda3/envs/fin/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-darwin.so, 2): Library not loaded: @rpath/libcblas.3.dylib
  Referenced from: /Users/officialbiznas/anaconda3/envs/fin/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-darwin.so
  Reason: image not found

In [23]:
#https://www.ncei.noaa.gov/support/access-data-service-api-user-documentation
dataTypes = 'WIND_DIR,WIND_SPEED,TEMP'
startDate = '2016-01-01'
endDate = '2016-01-02'
dataset= 'global-marine'# 'land-based-station/noaa-global-temp' #
url_orig = 'https://www.ncei.noaa.gov/access/services/data/v1?dataset=global-marine&dataTypes=WIND_DIR,WIND_SPEED&stations=AUCE&startDate=2016-01-01&endDate=2016-01-02&boundingBox=90,-180,-90,180'
url = 'https://www.ncei.noaa.gov/access/services/data/v1?dataset={}&dataTypes={}&stations=AUCE&startDate={}&endDate={}&boundingBox=90,-180,-90,180&includeAttributes=true&includeStationName=true' \
    .format(dataset, dataTypes, startDate, endDate)
print(url)
print(url_orig)

df = pd.read_csv(url)
df.tail()

https://www.ncei.noaa.gov/access/services/data/v1?dataset=global-marine&dataTypes=WIND_DIR,WIND_SPEED,TEMP&stations=AUCE&startDate=2016-01-01&endDate=2016-01-02&boundingBox=90,-180,-90,180&includeAttributes=true&includeStationName=true
https://www.ncei.noaa.gov/access/services/data/v1?dataset=global-marine&dataTypes=WIND_DIR,WIND_SPEED&stations=AUCE&startDate=2016-01-01&endDate=2016-01-02&boundingBox=90,-180,-90,180

,STATION,NAME,DATE,LATITUDE,LONGITUDE,TEMP,WIND_DIR,WIND_SPEED
5,AUCE,NaN,2016-01-02T09:09:00,-20.2,57.5,NaN,330,30
6,AUCE,NaN,2016-01-02T12:09:00,-20.2,57.5,NaN,330,40
7,AUCE,NaN,2016-01-02T15:09:00,-20.2,57.5,NaN,330,10
8,AUCE,NaN,2016-01-02T18:09:00,-20.2,57.5,NaN,300,30
9,AUCE,NaN,2016-01-02T21:09:00,-20.2,57.5,NaN,320,20

In [61]:

#https://www.ncei.noaa.gov/support/access-data-service-api-user-documentation
#https://www.ncdc.noaa.gov/cdo-web/datasets/GHCND/locations/FIPS:US/detail
dataTypes = 'PRCP,TAVG,TMAX,TMIN'#'DP01,DP05,DP10,DSND,DSNW,DT00,DT32,DX32,DX70,DX90,SNOW,PRCP'#'WIND_DIR,WIND_SPEED,TEMP'
startDate = '1952-01-01'
endDate = '1970-12-31'
dataset= 'daily-summaries'#'global-summary-of-the-month'#'global-marine'# 'land-based-station/noaa-global-temp' #
stations ='USW00014838'#'USW00014838' #-Marquettte WI #'USW00094728'
url_orig = 'https://www.ncei.noaa.gov/access/services/data/v1?dataset=global-summary-of-the-year&dataTypes={}&stations=ASN00084027&startDate=1952-01-01&endDate=1970-12-31&includeAttributes=true&format=csv'
url = 'https://www.ncei.noaa.gov/access/services/data/v1?dataset={}&dataTypes={}&stations={}&startDate={}&endDate={}&includeAttributes=true&format=csv' \
    .format(dataset, dataTypes, stations, startDate, endDate)
print(url)
print(url_orig)

df = pd.read_csv(url)
df.head()

https://www.ncei.noaa.gov/access/services/data/v1?dataset=daily-summaries&dataTypes=PRCP,TAVG,TMAX,PSUN&stations=USW00014838&startDate=1952-01-01&endDate=1970-12-31&includeAttributes=true&format=csv
https://www.ncei.noaa.gov/access/services/data/v1?dataset=global-summary-of-the-year&dataTypes={}&stations=ASN00084027&startDate=1952-01-01&endDate=1970-12-31&includeAttributes=true&format=csv

,STATION,DATE,PRCP,PRCP_ATTRIBUTES,PSUN,PSUN_ATTRIBUTES,TAVG,TAVG_ATTRIBUTES,TMAX,TMAX_ATTRIBUTES
0,USW00014838,1952-01-01,0,"T,,0,2400",NaN,NaN,NaN,NaN,17,",,0"
1,USW00014838,1952-01-02,0,"T,,0,2400",NaN,NaN,NaN,NaN,-72,",,0"
2,USW00014838,1952-01-03,0,"T,,0,2400",NaN,NaN,NaN,NaN,0,",,0"
3,USW00014838,1952-01-04,0,",,0,2400",NaN,NaN,NaN,NaN,6,",,0"
4,USW00014838,1952-01-05,0,"T,,0,2400",NaN,NaN,NaN,NaN,-28,",,0"

In [1]:

#https://www.ncei.noaa.gov/support/access-data-service-api-user-documentation
dataTypes = 'PRCP,TAVG'#'DP01,DP05,DP10,DSND,DSNW,DT00,DT32,DX32,DX70,DX90,SNOW,PRCP'#'WIND_DIR,WIND_SPEED,TEMP'
startDate = '1952-01-01'
endDate = '1970-12-31'
dataset= 'global-summary-of-the-month'#'global-marine'# 'land-based-station/noaa-global-temp' #
stations = 'USW00094728'
url_orig = 'https://www.ncei.noaa.gov/access/services/data/v1?dataset=global-summary-of-the-year&dataTypes={}&stations=ASN00084027&startDate=1952-01-01&endDate=1970-12-31&includeAttributes=true&format=csv'
url = 'https://www.ncei.noaa.gov/access/services/data/v1?dataset={}&dataTypes={}&stations={}&startDate={}&endDate={}&includeAttributes=true&format=csv' \
    .format(dataset, dataTypes, stations, startDate, endDate)
#print(url)
#print(url_orig)

df = pd.read_csv(url)
df.tail()

NameError: name 'pd' is not defined

In [4]:
#datasets https://www.ncdc.noaa.gov/data-access/quick-links
https://www.ncei.noaa.gov/products/land-based-station/noaa-global-temp
    
https://www.ncei.noaa.gov/access/services/data/v1?dataset=daily-summaries

  STATION                 DATE  LATITUDE  LONGITUDE  WIND_DIR  WIND_SPEED
5    AUCE  2016-01-02T09:09:00     -20.2       57.5       330          30
6    AUCE  2016-01-02T12:09:00     -20.2       57.5       330          40
7    AUCE  2016-01-02T15:09:00     -20.2       57.5       330          10
8    AUCE  2016-01-02T18:09:00     -20.2       57.5       300          30
9    AUCE  2016-01-02T21:09:00     -20.2       57.5       320          20